<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="ApricotFramework.Agentic.Tools" />
    <Using Include="ApricotFramework.Agentic.Tools.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.mtp" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="ApricotFramework.Grpc.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ApricotFramework.Agentic.Tools.Grpc.Client/ApricotFramework.Agentic.Tools.Grpc.Client.csproj" />
    <ProjectReference Include="../../src/ApricotFramework.Agentic.Tools.Grpc.Server/ApricotFramework.Agentic.Tools.Grpc.Server.csproj" />
  </ItemGroup>

</Project>
