<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ApricotFramework.Agentic.Tools.AspNetCore/ApricotFramework.Agentic.Tools.AspNetCore.csproj" />
  </ItemGroup>

</Project>
