using System.Collections.Concurrent;
using System.Text.Json;
using Microsoft.Extensions.AI;

namespace ApricotFramework.Agentic.Tools.Serialization;

/// <summary>
/// How a tool's arguments, results, and schemas are represented as JSON.
/// </summary>
/// <remarks>
/// <para>
/// One set of serializer options serves generation and serialization both, deliberately. A schema
/// generated under one set of options and a payload written under another disagree about property
/// names, and the disagreement surfaces as a model filling in fields that are silently dropped.
/// Which set that is comes from the tool - see <see cref="Microsoft.Extensions.AI.AIFunction.JsonSerializerOptions"/> - so a
/// host is not stuck with the default.
/// </para>
/// <para>
/// Schemas come from the annotated .NET type. <see cref="System.ComponentModel.DescriptionAttribute"/>
/// on a property becomes the description a model reads, and nullability becomes the difference
/// between a required field and an optional one - which is why a schema derived from a wire format
/// that cannot express absence, such as protobuf, is worth avoiding.
/// </para>
/// </remarks>
public static class AgentToolJson
{
    /// <summary>
    /// The options a tool uses unless it says otherwise.
    /// </summary>
    /// <remarks>
    /// The AI abstractions' own singleton. It is already what the schema generator assumes.
    /// </remarks>
    public static JsonSerializerOptions DefaultSerializerOptions => AIJsonUtilities.DefaultOptions;

    /// <summary>
    /// The schemas already generated by the type and the options they were generated under.
    /// </summary>
    private static readonly ConcurrentDictionary<(Type Type, JsonSerializerOptions Options), JsonElement> Cache = new();

    /// <summary>
    /// Gets the schema describing a tool's argument or result type.
    /// </summary>
    /// <typeparam name="T">The type to describe.</typeparam>
    /// <param name="serializerOptions">The options to generate under, or null for <see cref="DefaultSerializerOptions"/>.</param>
    /// <returns>The schema for the type.</returns>
    /// <remarks>
    /// Generated once per type and options pair. Generation walks reflection metadata, and a tool
    /// listing would otherwise repeat that work for every declaration on every call.
    /// </remarks>
    public static JsonElement Schema<T>(JsonSerializerOptions? serializerOptions = null)
    {
        return Schema(typeof(T), serializerOptions);
    }

    /// <summary>
    /// Gets the schema describing a type.
    /// </summary>
    /// <param name="type">The type to describe.</param>
    /// <param name="serializerOptions">The options to generate under, or null for <see cref="DefaultSerializerOptions"/>.</param>
    /// <returns>The schema for the type.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="type"/> is null.</exception>
    public static JsonElement Schema(Type type, JsonSerializerOptions? serializerOptions = null)
    {
        ArgumentNullException.ThrowIfNull(type);

        var options = serializerOptions ?? DefaultSerializerOptions;

        return Cache.GetOrAdd(
            (type, options),
            key => AIJsonUtilities.CreateJsonSchema(type: key.Type, serializerOptions: key.Options));
    }
}
